// <auto-generated />
namespace Recipes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedlikecollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedlikecollection));
        
        string IMigrationMetadata.Id
        {
            get { return "202408222029206_added-like-collection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
